### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/tets/256_tets.npz'

### ISSUE THREAD

**Issue by ChennyDeng** [elliottwu/MagicPony#1]
Hi, thanks for sharing the code!

I am trying to reproduce the MagicPony code. I have followed the instructions in readme, and tried to do testing on both horse and giraffe. The commands i used are
python run.py --config config/quadrupeds/test_giraffe_pretrained.yml --gpu 0 --num_workers 4
python run.py --config config/quadrupeds/test_horse.yml --gpu 0 --num_workers 4

However, i received the similar error message as shown below:
Loading configs from config/quadrupeds/test_giraffe_pretrained.yml
Environment: GPU 0 - seed 0
Loading testing data from data/giraffe_coco/test
/home/chenny/.conda/envs/magicpony/lib/python3.9/site-packages/torchvision/transforms/transforms.py:287: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "/mnt/nas/chenny/MagicPony/run.py", line 14, in <module>
    trainer = Trainer(cfgs, MagicPony)
  File "/mnt/nas/chenny/MagicPony/magicpony/trainer.py", line 53, in __init__
    self.model = model(cfgs)
  File "/mnt/nas/chenny/MagicPony/magicpony/model.py", line 48, in __init__
    self.netPrior = PriorPredictor(self.cfgs)
  File "/mnt/nas/chenny/MagicPony/magicpony/predictor.py", line 77, in __init__
    self.netShape = DMTetGeometry(
  File "/mnt/nas/chenny/MagicPony/magicpony/geometry/dmtet.py", line 179, in __init__
    self.load_tets(self.grid_res, self.grid_scale)
  File "/mnt/nas/chenny/MagicPony/magicpony/geometry/dmtet.py", line 203, in load_tets
    tets = np.load('data/tets/{}_tets.npz'.format(grid_res))
  File "/home/chenny/.conda/envs/magicpony/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/tets/256_tets.npz'

I wonder if you could kindly clarify where can i find  'data/tets/256_tets.npz'? I appreciate your time and effort in helping me. Thank you! Wish you a lovely day.

**Comment by elliottwu** [comment]
Hi, thanks for the heads up! Please use this script to download the tet grids:
https://github.com/elliottwu/MagicPony/blob/4ebaf90c90e25431e3fd65d05f7f8d0b1bb5da0d/data/tets/download_tets.sh
